Add http method, url, flavor and status_code attributes to client spans
trace4cats/trace4cats-http4s pull request #53
Opened 2021-12-08 21:24 UTC by mpichette-apple

2021-12-08 21:30 UTC, mpichette-apple commented on modules/http4s-client/src/main/scala/io/janstenpickle/trace4cats/http4s/client/Http4sClientRequest.scala
> +  val SemanticAttributeKeys_httpFlavor: String = "http.flavor"
I would be happy to move this into trace4cats-model if/once these changes are accepted.

2021-12-10 20:19 UTC, mpichette-apple commented on modules/http4s-client/src/main/scala/io/janstenpickle/trace4cats/http4s/client/Http4sClientRequest.scala
> +  val SemanticAttributeKeys_httpFlavor: String = "http.flavor"
preemptively created PR for it: https://github.com/trace4cats/trace4cats/pull/659

2021-12-18 07:57 UTC, catostrophe requested changes

2021-12-18 07:57 UTC, catostrophe commented on modules/http4s-client/src/main/scala/io/janstenpickle/trace4cats/http4s/client/Http4sClientResponse.scala
> +  }
```suggestion
  def toAttributes(res: Response_): Map[String, AttributeValue] =
    Map[String, AttributeValue](
      SemanticAttributeKeys.httpStatusCode -> res.status.code,
    )
```

2021-12-18 14:46 UTC, catostrophe approved these changes

2021-12-18 14:59 UTC, tarmath commented on modules/http4s-common/src/main/scala/io/janstenpickle/trace4cats/http4s/common/Http4sSpanNamer.scala
> +  val spanNameAttrOrHttpMethod: Http4sSpanNamer = req =>
This scheme is to allow people to manually specify a span name when they create the request, for times when either the default span namers just don't capture the essence of it, but also when folks want to name their client spans to give it more local context.

2021-12-18 15:00 UTC, catostrophe commented on modules/http4s-common/src/main/scala/io/janstenpickle/trace4cats/http4s/common/Http4sSpanNamer.scala
> +  val spanNameAttrOrHttpMethod: Http4sSpanNamer = req =>
Sure, I don't mind adding more namers. I just wondered if you had a useful snippet demonstrating this approach.

2021-12-18 15:53 UTC, catostrophe commented on modules/http4s-common/src/main/scala/io/janstenpickle/trace4cats/http4s/common/Http4sSpanNamer.scala
> +  val spanNameAttrOrHttpMethod: Http4sSpanNamer = req =>
@tarmath what if change it to the following?
```scala
def spanNameAttrOrElse(fallback: Http4sSpanNamer): Http4sSpanNamer = req =>
  req.attributes.lookup(Http4sAttributes.Keys.SpanName).getOrElse(fallback(req))
```

2021-12-18 15:56 UTC, tarmath commented on modules/http4s-common/src/main/scala/io/janstenpickle/trace4cats/http4s/common/Http4sSpanNamer.scala
> +  val spanNameAttrOrHttpMethod: Http4sSpanNamer = req =>
ahhh, wish I'd thought of it myself!

2021-12-18 16:09 UTC, catostrophe commented on modules/http4s-common/src/main/scala/io/janstenpickle/trace4cats/http4s/common/Http4sSpanNamer.scala
> +  val spanNameAttrOrHttpMethod: Http4sSpanNamer = req =>
fine. I'll fix and merge

2021-12-18 16:15 UTC, merged